# Generated by Django 6.0 on 2025-12-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Branch', models.CharField(max_length=20)),
            ],
        ),
    ]
